### ISSUE TITLE
Strange error while compiling

### ISSUE THREAD

**Issue by HoSnoopy** [AndreRH/hangover#103] opened 2021-01-13 16:19 UTC
## System Details

Raspberry Pi4 / 8GB RAM
running with Debian 10.7 / ARM64

## Problems Description

First I had this "clang not found error", then I followed this: https://github.com/AndreRH/hangover/issues/85

After about 1 hour compiling this came:
cd src && make install prefix='/usr/src/hangover/build/x86_64-w64-mingw32' exec_prefix='/usr/src/hangover/build/x86_64-w64-mingw32' libdir='/usr/src/hangover/build/x86_64-w64-mingw32/lib'
make[2]: Verzeichnis „/usr/src/hangover/build/libiconv64/src“ wird betreten
/bin/bash ../libtool --mode=link clang -L/usr/local/lib -I/usr/local/include iconv_no_i18n.o ../srclib/libicrt.a ../lib/libiconv.la iconv.res -o iconv_no_i18n
libtool: link: clang -I/usr/local/include iconv_no_i18n.o iconv.res -o iconv_no_i18n  -L/usr/local/lib ../srclib/libicrt.a ../lib/.libs/libiconv.a
iconv.res: file not recognized: file format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The process of compiling stopped here.

**Comment by AndreRH** [comment] 2021-01-14 09:26
Duplicate of #99

**Closed by AndreRH** 2021-01-14 09:26 UTC
